modLoader = "javafml"

loaderVersion = "${loader_version_range}"

license = "${mod_license}"
updateJSONURL = "https://raw.githubusercontent.com/roberttkahelin8/thingamajigs2addons/refs/heads/main/versions.json"
issueTrackerURL="https://github.com/roberttkahelin8/thingamajigs2addons/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"

logoFile="icon.png"
credits="Made by CreativeMasterBonin"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "thingamajigs"
type = "required"
versionRange = "[1.7.3,)"
ordering = "NONE"
side = "BOTH"